### ISSUE TITLE
Fix README.md filename

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [sukruenesatac/petclinic-microservices#1]
This file https://github.com/sukruenesatac/petclinic-microservices/blob/main/READMEE.md has an extra `E` in its name. 🙂

**Comment by sukruenesatac** [comment]
It was on purpose to not confuse another readme in same file. No need to make that perfect :D

**Comment by diego-ojeda-binbash** [comment]
@sukruenesatac sorry, I did not mean it like that. It's just that without the correct name, when you visit the home of this repo, you don't get the readme automatically displayed, which I think is nice touch. 🙂

**Comment by sukruenesatac** [comment]
Thanks for your consideration :) I'm actually thinking reorganise my github profile & repos, and review the projects to make them more representable.
